
list(APPEND PICOVIM_SOURCE
src/utils/timer.cpp
src/utils/timer.h
src/utils/stringutils.cpp
src/utils/stringutils.h
src/utils/threadutils.h
src/editor.cpp
src/editor.h
src/buffer.cpp
src/buffer.h
src/commands.cpp
src/commands.h
src/display_imgui.cpp
src/display_imgui.h
src/display.cpp
src/display.h
src/window.cpp
src/window.h
src/syntax.cpp
src/syntax.h
src/syntax_glsl.cpp
src/syntax_glsl.h
src/mode.cpp
src/mode.h
src/mode_standard.cpp
src/mode_standard.h
src/mode_vim.cpp
src/mode_vim.h
src/list.cmake
)
